### ISSUE TITLE
Align by menu greyed out

### ISSUE THREAD

**Issue by snorlaxium** [randy3k/AlignTab#42] opened 2015-01-24 01:51 UTC
When I select a block of text to align by I'm not getting options in the submenu to align by spaces

**Comment by randy3k** [comment] 2015-01-24 02:20
Would you explain more about your problems? I could help much if you just say that it does not work

**Comment by snorlaxium** [comment] 2015-01-24 02:28
So I downloaded the package and then installed it but when I highlight a block of text and click the Align By option in the menu I get a submenu of regex {First =, First :,  Spaces, etc.) but they're all greyed out and I can't click on any of these options. Just wondering why that's the case. To be more specific I'm on Sublime Text 2

**Comment by randy3k** [comment] 2015-01-24 02:40
I think ST2 is the reason. If you download the package from the master branch, it is only for ST3.
If you want a ST2 compatible version, check out the st2 branch.

Anyway, you should update the ST3 and I highly recommend it.

**Comment by randy3k** [comment] 2015-01-24 05:48
Closing it since it is not a bug.

**Closed by randy3k** 2015-01-24 05:48 UTC

**Comment by snorlaxium** [comment] 2015-01-24 07:17
I downloaded the one for ST2 though... I don't want to update to ST3 yet since it's still in the beta phase.

**Comment by randy3k** [comment] 2015-01-24 07:49
It has been in beta for always two years and many users and developers (including me) have already switched to ST3.
You will be missing a lot of amazing packages if you don't switch to ST3.

In fact, there are two more reasons to switch
1. ST2 has out of maintenance, there's no point to stay in ST2
2. ST3 has been very stable. I, personally, have never encountered any issues.
